local map = require ('util').map

local add, later = MiniDeps.add, MiniDeps.later

later (function ()
  add ({
    source = 'ibhagwan/fzf-lua',
  })

  local fzf = require ('fzf-lua')

  fzf.setup ({
    files = {
      previewer = 'bat',
    },
  })

  --
  -- Buffers and Files
  --
  map ('<leader>ff', fzf.files, 'Files [Fzf]')
  map ('<leader>fx', function ()
    fzf.files ({ cwd = '~' })
  end, 'Global [Fzf]')
  map ('<leader>fc', function ()
    fzf.files ({ cwd = '~/.config' })
  end, 'Config [Fzf]')
  map ('<leader>fb', function ()
    fzf.buffers ()
  end, 'Buffers [Fzf]')
  map ('<leader>fo', function ()
    fzf.oldfiles ()
  end, 'Recent files [Fzf]')
  map ('<leader>fq', function ()
    fzf.quickfix ()
  end, 'Quickfix list [Fzf]')
  map ('<leader>fQ', function ()
    fzf.quickfix_stack ()
  end, 'Quickfix stack [Fzf]')
  map ('<leader>fc', function ()
    fzf.loclist ()
  end, 'Loclist list [Fzf]')
  map ('<leader>fC', function ()
    fzf.loclist_stack ()
  end, 'Loclist stack [Fzf]')
  map ('<leader>fn', function ()
    fzf.lines ()
  end, 'Open buffers lines [Fzf]')
  map ('<leader>fN', function ()
    fzf.blines ()
  end, 'Current buffer lines [Fzf]')
  map ('<leader>fT', function ()
    fzf.treesitter ()
  end, 'Current buffer Treesitter symbols [Fzf]')
  map ('<leader>ft', function ()
    fzf.tabs ()
  end, 'Open tabs [Fzf]')
  map ('<leader>fa', function ()
    fzf.args ()
  end, 'Argument list [Fzf]')

  --
  -- Search
  --
  map ('<leader>fwg', function ()
    fzf.grep ()
  end, 'Search pattern [Fzf]')
  map ('<leader>fwl', function ()
    fzf.grep_last ()
  end, 'Search last pattern [Fzf]')
  map ('<leader>fww', function ()
    fzf.cword ()
  end, 'Search word under cursor [Fzf]')
  map ('<leader>fwW', function ()
    fzf.cWORD ()
  end, 'Search WORD under cursor [Fzf]')
  map ('<leader>fwV', function ()
    fzf.grep_visual ()
  end, 'Search visual selection [Fzf]')
  map ('<leader>fwp', function ()
    fzf.grep_project ()
  end, 'Search all project lines [Fzf]')
  map ('<leader>fwb', function ()
    fzf.grep_curbuf ()
  end, 'Search current buffer lines [Fzf]')
  map ('<leader>fwq', function ()
    fzf.quickfix ()
  end, 'Search the quickfix list [Fzf]')
  map ('<leader>fwc', function ()
    fzf.loclist ()
  end, 'Search the loccation list [Fzf]')

  map ('<leader>fwv', function ()
    fzf.live_grep ()
  end, 'Live grep current project [Fzf]')
  map ('<leader>fwr', function ()
    fzf.live_grep_resume ()
  end, 'Live grep last search [Fzf]')
  map ('<leader>fwf', function ()
    fzf.lgrep_curbuf ()
  end, 'Live grep curent buffer [Fzf]')
  map ('<leader>fwx', function ()
    fzf.lgre_quickfix ()
  end, 'Live grep the quickfix list [Fzf]')
  map ('<leader>fws', function ()
    fzf.lgrep_loclist ()
  end, 'Live grep the location list[Fzf]')
  map ('<leader>fwo', function ()
    fzf.live_grep_glob ()
  end, 'Live grep "rg --glob" [Fzf]')
  map ('<leader>fwG', function ()
    fzf.live_grep_native ()
  end, 'Live grep native [Fzf]')

  --
  -- LSP
  --
  map ('<leader>flr', function ()
    fzf.lsp_references ()
  end, 'LSP References [Fzf]')
  map ('<leader>fld', function ()
    fzf.lsp_definitions ()
  end, 'LSP Definitions [Fzf]')
  map ('<leader>flD', function ()
    fzf.declarations ()
  end, 'LSP Declarations [Fzf]')
  map ('<leader>flt', function ()
    fzf.typedefs ()
  end, 'LSP Type Definitions [Fzf]')
  map ('<leader>fli', function ()
    fzf.implementations ()
  end, 'LSP Implementations [Fzf]')
  map ('<leader>fls', function ()
    fzf.lsp_document_symbols ()
  end, 'LSP Document Symbols [Fzf]')
  map ('<leader>flw', function ()
    fzf.lsp_workspace_symbols ()
  end, 'LSP Workspace Symbols [Fzf]')
  map ('<leader>flW', function ()
    fzf.lsp_live_workspace_symbols ()
  end, 'LSP Workspace Symbols (live query) [Fzf]')
  map ('<leader>fla', function ()
    fzf.code_actions ()
  end, 'LSP Code Actions [Fzf]')
  map ('<leader>flF', function ()
    fzf.lsp_finder ()
  end, 'LSP Locations, combined view [Fzf]')
  map ('<leader>flg', function ()
    fzf.diagnostics_document ()
  end, 'LSP Diagnostics Document [Fzf]')
  map ('<leader>flG', function ()
    fzf.diagnostics_workspace ()
  end, 'LSP Diagnostics Workspace [Fzf]')

  --
  -- Zoxide
  --
  map ('<leader>Z', function ()
    fzf.zoxide ()
  end, 'Zoxide [Fzf]')
end)
